### ISSUE TITLE
activiti 5.3-SNAPSHOT?

### ISSUE THREAD

**Issue by banq** [mproch/activitiWebappSample#1]
in your pom.xml, you wrote a activiti version 5.3-SNAPSHOT, but there is no it

**Comment by mproch** [comment]
Hello @banq. As it's written in README - you have to build activiti from sources to use it as released version at that time didn't have appropriate dependencies. Having said that - I suppose this sample is not really usable anymore - activiti has gone a looong way in last 8 years...
